[variables]
NPM_CONFIG_PRODUCTION = "true"

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm", "python3", "gcc", "sqlite"]
aptPkgs = ["python3-dev", "build-essential"]

[phases.build]
cmds = [
  "cd railway-deploy",
  "npm ci --only=production"
]

[phases.start]
cmd = "cd railway-deploy && npm start"

[build]
context = "./railway-deploy" 